//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class poseduje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public poseduje()
        {
            this.vozna_linija = new HashSet<vozna_linija>();
            this.mehanicars = new HashSet<mehanicar>();
        }
    
        public string autobus_brtablica { get; set; }
        public int autobuska_stanica_idstanice { get; set; }
    
        public virtual autobu autobu { get; set; }
        public virtual autobuska_stanica autobuska_stanica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vozna_linija> vozna_linija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mehanicar> mehanicars { get; set; }
    }
}
