//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class putnik
    {
        public int idputnika { get; set; }
        public string ime { get; set; }
        public string karta_idkarte { get; set; }
    
        public virtual karta karta { get; set; }
    }
}
